### ISSUE TITLE
BINANCE error 5 "binanceErrorMissingAccountKeys"

### ISSUE THREAD

**Issue by michnicki** [dmikushin/bitrader#1]
Hi,

thanks for this! After compiling the bot, I get confronted with the following error:

```
Initializing ...
Finding current positions ...
BINANCE error 5 "binanceErrorMissingAccountKeys" on localhost at /opt/bitrader/bitrader.cpp:71
You may want to set FREEZE_ON_ERROR environment variable to debug the case

```

How can I fix this?

**Comment by dmikushin** [comment]
The bot searches for api/secret keys for Binance user account and reports error in case of failure. These keys are needed to get the available funds info and to perform buy/sell orders.

The keys are expected to be located in:

```
$HOME/.bitrader/key
$HOME/.bitrader/secret
```

**Comment by dmikushin** [comment]
95f506ab50147ca324355773266d4a43b1ed59a4 adds a helpful message
